version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"  # MinIO Console port
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data
  apicurio:
    image: apicurio/apicurio-registry-mem:2.2.5.Final
    ports:
      - 8085:8080
  kafka-connect:
    build:
      context: ./kafka
      dockerfile: ./Dockerfile
    container_name: kafka-connect
    ports:
      - "${KAFKA_CONNECT_PORT}:8083"  # Kafka Connect REST API port
    environment:
      - BOOTSTRAP_SERVERS=${BOOTSTRAP_SERVERS}
      - GROUP_ID=${GROUP_ID}
      - CONFIG_STORAGE_TOPIC=${CONFIG_STORAGE_TOPIC}
      - OFFSET_STORAGE_TOPIC=${OFFSET_STORAGE_TOPIC}
      - STATUS_STORAGE_TOPIC=${STATUS_STORAGE_TOPIC}
      - ENABLE_APICURIO_CONVERTERS=true
      - CONNECT_PLUGIN_PATH=/kafka/connect/
    depends_on:
      - minio
      - apicurio

  kafka-connect-ui:
    image: landoop/kafka-connect-ui:0.9.7
    container_name: kafka-connect-ui
    ports:
      - "${KAFKA_CONNECT_UI_PORT}:8000"  # UI port
    environment:
      - CONNECT_URL=${CONNECT_URL}  # Kafka Connect REST API URL
      - PORT=8000  # Port for Kafka Connect UI
    depends_on:
      - kafka-connect